version: 2
build:
  image: latest
python:
  version: "3.8"
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false