
name: Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      - uses: abatilo/actions-poetry@8284d202bc272a8d0597e26e1c0b4a0d0c73db93
      
      - name: Install dependencies
        run: poetry install

      - name: Tag
        run: git tag $(poetry run python -c "import pystematic; print(f'v{pystematic.__version__}')") && git push --tags

      - name: Build wheel
        run: poetry build -f wheel

      - name: Publish to pypi
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
